language: python
env:
  - DJANGO_VERSION=1.11.7
install:
  - python setup.py -q install
python:
  - "3.6.3"
# command to install dependencies
install:
  - pip install pyyaml
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install coveralls
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test myApp
  - coverage run --source='.' manage.py test
after_success: coveralls
