# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='nowhere', max_length=200),
            preserve_default=False,
        ),
    ]
